[versions]
modDevGradle = "2.0.99"
neoForge = "21.1.186"
minecraft = "1.21.1"
parchment = "2024.11.17"
lombok = "8.7.1"
registrate = "MC1.21-1.3.0+55"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version.ref = "registrate" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }